name: ci
 
on:
 push:
   branches: master
 
jobs:
 main:
   runs-on: ubuntu-latest
   steps:     
     - name: Setup Docker Buildx
       uses: docker/setup-buildx-action@v1
     - name: check the path
       run: echo "ğŸ‰ github.event_name =  ${{ github.event_name }} ."
       run: echo "ğŸ§ runner.os =  ${{ runner.os }} "
       run: echo "ğŸ” github.ref = ${{ github.ref }} ."
       run: echo "ğŸ’¡ github.repository =  ${{ github.repository }}."
        
       run: echo "ğŸ job.status =  ${{ job.status }}."

     - name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
     
     - name: Build and push api
       id: docker_build_api
       uses: docker/build-push-action@v2
       if: contains(github.repository, 'Docker_NodeAPI')
       with:
         file: /Docker_NodeAPI/Dockerfile
         push: true
         tags: mfrony2003/api_cicd:latest

     - name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
     
     - name: Build and push app
       id: docker_build_app
       if: contains(github.repository, 'Docker_React')
       uses: docker/build-push-action@v2
       with:
         file: /Docker_React/Dockerfile
         push: true
         tags: mfrony2003/app_cicd:latest